version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: weekly
      time: "21:00"
      day: sunday
    open-pull-requests-limit: 10
    groups:
      rand:
        patterns:
        - "rand*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "21:00"
      day: sunday
    open-pull-requests-limit: 3
