---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: cargo-deps
  image: rust:1.64
  commands:
  - cargo fetch
  environment:
    CARGO_HOME: /drone/src/.cargo
  depends_on:
  - git-clone

- name: cargo-format
  image: rust:1.64
  commands:
  - rustup component add rustfmt && cargo fmt --all -- --check
  environment:
    CARGO_HOME: /drone/src/.cargo
  depends_on:
  - cargo-deps

- name: cargo-doc-ci
  image: rust:1.64
  commands:
  - cargo doc --document-private-items --workspace --all-features --no-deps
  environment:
    RUSTDOCFLAGS: -Dwarnings
  depends_on:
  - cargo-format

- name: cargo-clippy-ci
  image: rust:1.64
  commands:
  - rustup component add clippy 
  - cargo clippy --workspace -- -D warnings
  - cargo clippy --workspace --all-features -- -D warnings 
  - cargo clippy --workspace --release -- -D warnings 
  - cargo clippy --workspace --release --all-features -- -D warnings
  environment:
    BUILD_ENV: dev
    CARGO_HOME: /drone/src/.cargo
  depends_on:
  - cargo-doc-ci

- name: cargo-test
  image: rust:1.64
  commands:
  - cargo test --all && cargo test --all --features toggle
  environment:
    BUILD_ENV: dev
    CARGO_HOME: /drone/src/.cargo
  depends_on:
  - cargo-clippy-ci

trigger:
  event:
  - push

---
kind: pipeline
name: build-production

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: build-production
  image: rust:1.64
  commands:
  - ./deploy/build production
  environment:
    CARGO_AUTH_KEY:
      from_secret: cargo_auth_key
  depends_on:
  - git-clone

trigger:
  event:
  - tag
  ref:
  - refs/tags/*.*.*

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: public.ecr.aws/prima/drone-email
  settings:
    from: drone@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

trigger:
  status:
  - failure
  target:
    exclude:
    - qa-stack
    - qa-it
    - qa

depends_on:
- default
- build-production

---
kind: signature
hmac: 66badf18a9b2157be8df165e445ffeb0d793c1a9031ad1aafb32f30da1a0edfd

...
