--- kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: cargo-deps
  image: rust:1.61
  commands:
  - cargo fetch
  environment:
    CARGO_HOME: /drone/src/.cargo
  depends_on:
  - git-clone

- name: cargo-format
  image: rust:1.61
  commands:
  - cargo fmt --all -- --check
  environment:
    CARGO_HOME: /drone/src/.cargo
  depends_on:
  - cargo-deps

- name: cargo-clippy-ci
  image: rust:1.61
  commands:
  - cargo clippy -- -D warnings && cargo clippy --features toggle -- -D warnings
  environment:
    BUILD_ENV: dev
    CARGO_HOME: /drone/src/.cargo
  depends_on:
  - cargo-format

- name: cargo-test
  image: rust:1.61
  commands:
  - cargo test --all && cargo test --all --features toggle
  environment:
    BUILD_ENV: dev
    CARGO_HOME: /drone/src/.cargo
    CARGO_HTTP_CAINFO: ""
  depends_on:
  - cargo-clippy-ci

- name: cargo-build
  image: rust:1.61
  commands:
  - cargo build -j 2 --all-features
  environment:
    BUILD_ENV: dev
    CARGO_HOME: /drone/src/.cargo
  when:
    branch:
      exclude:
      - master
  depends_on:
  - cargo-test

trigger:
  event:
  - push

---
kind: pipeline
name: build-production

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

#- name: build-production
#  image: rust:1.61
#  commands:
#  - . /etc/profile.d/ecs-credentials-endpoint
#  - ./deploy/build production
#  environment:
#    CARGO_AUTH_KEY:
#      from_secret: cargo_auth_key
#  volumes:
#  - name: ecs
#    path: /etc/profile.d/ecs-credentials-endpoint
#  depends_on:
#  - build-image

trigger:
  event:
  - tag
  ref:
  - refs/tags/*.*.*

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: public.ecr.aws/prima/drone-email
  settings:
    from: drone@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

trigger:
  status:
  - failure
  target:
    exclude:
    - qa-stack
    - qa-it
    - qa

depends_on:
- default
- build-production
