apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "veil"
  description: "veil"
spec:
  type: "library"
  lifecycle: production
  owner: "group:default/team-developer-experience"
  system: prima.it
