[package]
name = "veil-tests-environment-aware"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
parking_lot = "0.12" # needed for non-poisoning mutex
veil = { path = "../../", features = ["environment-aware"] }
veil-tests = { path = "../" }
