[package]
name = "veil-tests-environment-aware-disable"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
veil = { path = "../../", features = ["environment-aware"] }
veil-tests = { path = "../" }
