name: Continuous Integration

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --all-features
      - name: Build docs
        run:  cargo doc --document-private-items --workspace --all-features --no-deps
      - name: Run tests for no features
        run: cargo test --all 
      - name: Run tests with toggle feature
        run: cargo test --all --features toggle
    env:
      RUSTDOCFLAGS: -Dwarnings
